
// This file has been generated by the GUI designer. Do not modify.
namespace Launchpad.Utilities
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.Alignment alignment14;
		
		private global::Gtk.FileChooserWidget fileChooser;
		
		private global::Gtk.Alignment alignment12;
		
		private global::Gtk.HSeparator hseparator3;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Alignment alignment18;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Alignment alignment19;
		
		private global::Gtk.Label progressLabel;
		
		private global::Gtk.Alignment alignment17;
		
		private global::Gtk.ProgressBar progressbar;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Alignment alignment15;
		
		private global::Gtk.Button generateManifestButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Launchpad.Utilities.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 640;
			this.HeightRequest = 384;
			this.Name = "Launchpad.Utilities.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Launchpad Utilities - Manifest");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Launchpad.Utilities.Resources.Icons8-Android-Industry-Engineering.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Launchpad.Utilities.MainWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'/></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox3.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment14 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			this.alignment14.LeftPadding = ((uint)(8));
			this.alignment14.RightPadding = ((uint)(8));
			// Container child alignment14.Gtk.Container+ContainerChild
			this.fileChooser = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(2)));
			this.fileChooser.Name = "fileChooser";
			this.fileChooser.LocalOnly = false;
			this.alignment14.Add (this.fileChooser);
			this.vbox3.Add (this.alignment14);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment14]));
			w4.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			// Container child alignment12.Gtk.Container+ContainerChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.alignment12.Add (this.hseparator3);
			this.vbox3.Add (this.alignment12);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment12]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment18 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment18.Name = "alignment18";
			this.alignment18.LeftPadding = ((uint)(8));
			// Container child alignment18.Gtk.Container+ContainerChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Progress: ");
			this.alignment18.Add (this.label4);
			this.hbox4.Add (this.alignment18);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment18]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment19 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment19.Name = "alignment19";
			this.alignment19.RightPadding = ((uint)(8));
			// Container child alignment19.Gtk.Container+ContainerChild
			this.progressLabel = new global::Gtk.Label ();
			this.progressLabel.Name = "progressLabel";
			this.progressLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("/some/file/path : 1 out of 100");
			this.alignment19.Add (this.progressLabel);
			this.hbox4.Add (this.alignment19);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment19]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment17 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment17.Name = "alignment17";
			this.alignment17.LeftPadding = ((uint)(8));
			this.alignment17.RightPadding = ((uint)(8));
			// Container child alignment17.Gtk.Container+ContainerChild
			this.progressbar = new global::Gtk.ProgressBar ();
			this.progressbar.Name = "progressbar";
			this.alignment17.Add (this.progressbar);
			this.vbox3.Add (this.alignment17);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment17]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			this.alignment15.RightPadding = ((uint)(8));
			this.alignment15.BottomPadding = ((uint)(8));
			// Container child alignment15.Gtk.Container+ContainerChild
			this.generateManifestButton = new global::Gtk.Button ();
			this.generateManifestButton.CanFocus = true;
			this.generateManifestButton.Name = "generateManifestButton";
			this.generateManifestButton.UseUnderline = true;
			this.generateManifestButton.Label = global::Mono.Unix.Catalog.GetString ("Generate Manifest");
			this.alignment15.Add (this.generateManifestButton);
			this.hbox3.Add (this.alignment15);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment15]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w16.Position = 6;
			w16.Expand = false;
			w16.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 640;
			this.DefaultHeight = 384;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.generateManifestButton.Clicked += new global::System.EventHandler (this.OnGenerateManifestButtonClicked);
		}
	}
}
