
// This file has been generated by the GUI designer. Do not modify.

using Gdk;
using Gtk;
using Stetic;
using Image = Gtk.Image;

namespace Launchpad.Launcher.Interface
{
	public sealed partial class MainWindow
	{
		private UIManager UIManager;

		private Action ActionsAction1;

		private Action refreshAction1;

		private VBox vbox1;

		private MenuBar menubar1;

		private HBox hbox2;

		private VBox BrowserContainer;

		private Alignment alignment2;

		private ScrolledWindow ScrolledBrowserWindow;

		private Alignment alignment5;

		private Image GameBanner;

		private Alignment alignment1;

		private Label IndicatorLabel;

		private HBox hbox3;

		private Alignment alignment4;

		private ProgressBar MainProgressBar;

		private HBox hbox4;

		private Alignment alignment3;

		private Button PrimaryButton;

		private void Build ()
		{
			Gui.Initialize (this);

			// Widget Launchpad.Launcher.UnixUI.MainWindow
			this.UIManager = new UIManager ();
			ActionGroup w1 = new ActionGroup ("Default");

			this.ActionsAction1 = new Action("ActionsAction1", LocalizationCatalog.GetString("Actions"), null, null)
			{
				ShortLabel = LocalizationCatalog.GetString("Actions")
			};
			w1.Add (this.ActionsAction1, null);

			this.refreshAction1 = new Action("refreshAction1", LocalizationCatalog.GetString("Repair Game"), null,
				"gtk-refresh")
			{
				ShortLabel = LocalizationCatalog.GetString("Repair Game")
			};
			w1.Add (this.refreshAction1, null);

			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Launchpad.Launcher.UnixUI.MainWindow";
			this.Title = LocalizationCatalog.GetString ("Launchpad - <GameName>");
			this.Icon = Pixbuf.LoadFromResource ("Launchpad.Launcher.Resources.RocketIcon.ico");
			this.WindowPosition = (WindowPosition)4;
			this.DefaultWidth = 755;
			this.DefaultHeight = 412;

			// Container child Launchpad.Launcher.UnixUI.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new VBox
			{
				Name = "vbox1",
				Spacing = 6
			};

			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ActionsAction1' action='ActionsAction1'><menuitem name='refreshAction1' action='refreshAction1'/></menu></menubar></ui>");
			this.menubar1 = (MenuBar)this.UIManager.GetWidget ("/menubar1");
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);

			Box.BoxChild w2 = (Box.BoxChild)this.vbox1 [this.menubar1];
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;

			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new HBox
			{
				Name = "hbox2",
				Spacing = 6,
				BorderWidth = 4
			};

			// Container child hbox2.Gtk.Box+BoxChild
			this.BrowserContainer = new VBox
			{
				Name = "BrowserContainer",
				Spacing = 6
			};

			// Container child BrowserContainer.Gtk.Box+BoxChild
			this.alignment2 = new Alignment(0.5F, 0.5F, 1F, 1F)
			{
				WidthRequest = 300,
				Name = "alignment2"
			};

			// Container child alignment2.Gtk.Container+ContainerChild
			this.ScrolledBrowserWindow = new ScrolledWindow
			{
				WidthRequest = 290,
				HeightRequest = 300,
				CanFocus = true,
				Name = "ScrolledBrowserWindow",
				ShadowType = ShadowType.In
			};
			this.alignment2.Add (this.ScrolledBrowserWindow);
			this.BrowserContainer.Add (this.alignment2);

			Box.BoxChild w4 = (Box.BoxChild)this.BrowserContainer [this.alignment2];
			w4.Position = 0;
			this.hbox2.Add (this.BrowserContainer);

			Box.BoxChild w5 = (Box.BoxChild)this.hbox2 [this.BrowserContainer];
			w5.Position = 0;
			w5.Expand = false;

			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment5 = new Alignment(0.5F, 0.5F, 1F, 1F)
			{
				Name = "alignment5"
			};

			// Container child alignment5.Gtk.Container+ContainerChild
			this.GameBanner = new Image
			{
				WidthRequest = 450,
				HeightRequest = 300,
				Name = "GameBanner",
				Pixbuf = Pixbuf.LoadFromResource("Launchpad.Launcher.Resources.RocketIcon.ico")
			};
			this.alignment5.Add (this.GameBanner);
			this.hbox2.Add (this.alignment5);

			Box.BoxChild w7 = (Box.BoxChild)this.hbox2 [this.alignment5];
			w7.Position = 1;
			this.vbox1.Add (this.hbox2);

			Box.BoxChild w8 = (Box.BoxChild)this.vbox1 [this.hbox2];
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;

			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new Alignment(0.5F, 0.5F, 1F, 1F)
			{
				Name = "alignment1",
				LeftPadding = 6
			};

			// Container child alignment1.Gtk.Container+ContainerChild
			this.IndicatorLabel = new Label
			{
				Name = "IndicatorLabel",
				Xalign = 0F,
				LabelProp = LocalizationCatalog.GetString("Idle")
			};
			this.alignment1.Add (this.IndicatorLabel);
			this.vbox1.Add (this.alignment1);

			Box.BoxChild w10 = (Box.BoxChild)this.vbox1 [this.alignment1];
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;

			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new HBox
			{
				Name = "hbox3",
				Spacing = 6,
				BorderWidth = 4
			};

			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment4 = new Alignment(0.5F, 0.5F, 1F, 1F)
			{
				Name = "alignment4"
			};

			// Container child alignment4.Gtk.Container+ContainerChild
			this.MainProgressBar = new ProgressBar
			{
				Name = "MainProgressBar"
			};
			this.alignment4.Add (this.MainProgressBar);
			this.hbox3.Add (this.alignment4);

			Box.BoxChild w12 = (Box.BoxChild)this.hbox3 [this.alignment4];
			w12.Position = 0;

			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new HBox
			{
				Name = "hbox4",
				Spacing = 6
			};

			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment3 = new Alignment(0.5F, 0.5F, 1F, 1F)
			{
				WidthRequest = 100,
				Name = "alignment3"
			};

			// Container child alignment3.Gtk.Container+ContainerChild
			this.PrimaryButton = new Button
			{
				Sensitive = false,
				CanDefault = true,
				CanFocus = true,
				Name = "PrimaryButton",
				UseUnderline = true,
				Label = LocalizationCatalog.GetString("Inactive")
			};
			this.alignment3.Add (this.PrimaryButton);
			this.hbox4.Add (this.alignment3);

			Box.BoxChild w14 = (Box.BoxChild)this.hbox4 [this.alignment3];
			w14.Position = 0;
			this.hbox3.Add (this.hbox4);

			Box.BoxChild w15 = (Box.BoxChild)this.hbox3 [this.hbox4];
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.hbox3);

			Box.BoxChild w16 = (Box.BoxChild)this.vbox1 [this.hbox3];
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;

			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.PrimaryButton.HasDefault = true;
			this.Show ();
			this.DeleteEvent += this.OnDeleteEvent;
			this.refreshAction1.Activated += this.OnRepairGameActionActivated;
			this.PrimaryButton.Clicked += this.OnPrimaryButtonClicked;
		}
	}
}
