//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launchpad.Launcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launchpad.Launcher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelString {
            get {
                return ResourceManager.GetString("cancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Settings.
        /// </summary>
        internal static string editSettingsTitle {
            get {
                return ResourceManager.GetString("editSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editString {
            get {
                return ResourceManager.GetString("editString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launchpad - Error.
        /// </summary>
        internal static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file {0}: {1} of {2} bytes..
        /// </summary>
        internal static string fileDownloadMessage {
            get {
                return ResourceManager.GetString("fileDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the FTP server. Please check your FTP settings..
        /// </summary>
        internal static string ftpConnectionFailureMessage {
            get {
                return ResourceManager.GetString("ftpConnectionFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server..
        /// </summary>
        internal static string ftpConnectionFailureString {
            get {
                return ResourceManager.GetString("ftpConnectionFailureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Password: .
        /// </summary>
        internal static string ftpPasswordString {
            get {
                return ResourceManager.GetString("ftpPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP URL:.
        /// </summary>
        internal static string ftpURLString {
            get {
                return ResourceManager.GetString("ftpURLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Username: .
        /// </summary>
        internal static string ftpUsernameString {
            get {
                return ResourceManager.GetString("ftpUsernameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game download failed. Are you missing the manifest?.
        /// </summary>
        internal static string gameDownloadFailMessage {
            get {
                return ResourceManager.GetString("gameDownloadFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game download finished. Play away!.
        /// </summary>
        internal static string gameDownloadFinishedMessage {
            get {
                return ResourceManager.GetString("gameDownloadFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name:.
        /// </summary>
        internal static string gameNameString {
            get {
                return ResourceManager.GetString("gameNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string idleString {
            get {
                return ResourceManager.GetString("idleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launchpad - Info.
        /// </summary>
        internal static string infoTitle {
            get {
                return ResourceManager.GetString("infoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This appears to be the first time you&apos;re starting the launcher.
        ///Is this the location where you would like to install the game?
        ///
        ///{0}.
        /// </summary>
        internal static string initialStartupMessage {
            get {
                return ResourceManager.GetString("initialStartupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string installingLabel {
            get {
                return ResourceManager.GetString("installingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string installLabel {
            get {
                return ResourceManager.GetString("installLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageString {
            get {
                return ResourceManager.GetString("languageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game failed to launch. Try repairing the installation..
        /// </summary>
        internal static string launchFailMessage {
            get {
                return ResourceManager.GetString("launchFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launchpad - Failed to launch the game!.
        /// </summary>
        internal static string launchFailTitle {
            get {
                return ResourceManager.GetString("launchFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching....
        /// </summary>
        internal static string launchingLabel {
            get {
                return ResourceManager.GetString("launchingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        internal static string launchLabel {
            get {
                return ResourceManager.GetString("launchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux.
        /// </summary>
        internal static string linuxTarget {
            get {
                return ResourceManager.GetString("linuxTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Local&lt;/b&gt;.
        /// </summary>
        internal static string localSettingsTitle {
            get {
                return ResourceManager.GetString("localSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac.
        /// </summary>
        internal static string macTarget {
            get {
                return ResourceManager.GetString("macTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL needs to begin with &quot;ftp://&quot;. Please correct the URL..
        /// </summary>
        internal static string malformedFTPURLMessage {
            get {
                return ResourceManager.GetString("malformedFTPURLMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server does not provide the game for the selected platform..
        /// </summary>
        internal static string noPlatformMessage {
            get {
                return ResourceManager.GetString("noPlatformMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launchpad - Platform not provided!.
        /// </summary>
        internal static string noPlatformTitle {
            get {
                return ResourceManager.GetString("noPlatformTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string okString {
            get {
                return ResourceManager.GetString("okString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string optionsString {
            get {
                return ResourceManager.GetString("optionsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Remote&lt;/b&gt;.
        /// </summary>
        internal static string remoteSettingsTitle {
            get {
                return ResourceManager.GetString("remoteSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launchpad has finished repairing the game installation. Play away!.
        /// </summary>
        internal static string repairFinishMessage {
            get {
                return ResourceManager.GetString("repairFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launchpad - Game repair finished.
        /// </summary>
        internal static string repairFinishTitle {
            get {
                return ResourceManager.GetString("repairFinishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing....
        /// </summary>
        internal static string repairingLabel {
            get {
                return ResourceManager.GetString("repairingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string repairLabel {
            get {
                return ResourceManager.GetString("repairLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsString {
            get {
                return ResourceManager.GetString("settingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Target:.
        /// </summary>
        internal static string systemTargetString {
            get {
                return ResourceManager.GetString("systemTargetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string updateLabel {
            get {
                return ResourceManager.GetString("updateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        internal static string updatingLabel {
            get {
                return ResourceManager.GetString("updatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous useage stats are not enabled..
        /// </summary>
        internal static string usageTitle {
            get {
                return ResourceManager.GetString("usageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying....
        /// </summary>
        internal static string verifyingMessage {
            get {
                return ResourceManager.GetString("verifyingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launchpad - Warning.
        /// </summary>
        internal static string warningTitle {
            get {
                return ResourceManager.GetString("warningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32.
        /// </summary>
        internal static string win32Target {
            get {
                return ResourceManager.GetString("win32Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win64.
        /// </summary>
        internal static string win64Target {
            get {
                return ResourceManager.GetString("win64Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launchpad - &lt;GameName&gt;.
        /// </summary>
        internal static string windowTitle {
            get {
                return ResourceManager.GetString("windowTitle", resourceCulture);
            }
        }
    }
}
