// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Launchpad.Launcher.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Launchpad.Launcher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string cancelString {
            get {
                return ResourceManager.GetString("cancelString", resourceCulture);
            }
        }
        
        internal static string editSettingsTitle {
            get {
                return ResourceManager.GetString("editSettingsTitle", resourceCulture);
            }
        }
        
        internal static string editString {
            get {
                return ResourceManager.GetString("editString", resourceCulture);
            }
        }
        
        internal static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        internal static string fileDownloadMessage {
            get {
                return ResourceManager.GetString("fileDownloadMessage", resourceCulture);
            }
        }
        
        internal static string ftpConnectionFailureMessage {
            get {
                return ResourceManager.GetString("ftpConnectionFailureMessage", resourceCulture);
            }
        }
        
        internal static string ftpConnectionFailureString {
            get {
                return ResourceManager.GetString("ftpConnectionFailureString", resourceCulture);
            }
        }
        
        internal static string ftpPasswordString {
            get {
                return ResourceManager.GetString("ftpPasswordString", resourceCulture);
            }
        }
        
        internal static string ftpURLString {
            get {
                return ResourceManager.GetString("ftpURLString", resourceCulture);
            }
        }
        
        internal static string ftpUsernameString {
            get {
                return ResourceManager.GetString("ftpUsernameString", resourceCulture);
            }
        }
        
        internal static string gameDownloadFailMessage {
            get {
                return ResourceManager.GetString("gameDownloadFailMessage", resourceCulture);
            }
        }
        
        internal static string gameDownloadFinishedMessage {
            get {
                return ResourceManager.GetString("gameDownloadFinishedMessage", resourceCulture);
            }
        }
        
        internal static string gameNameString {
            get {
                return ResourceManager.GetString("gameNameString", resourceCulture);
            }
        }
        
        internal static string idleString {
            get {
                return ResourceManager.GetString("idleString", resourceCulture);
            }
        }
        
        internal static string infoTitle {
            get {
                return ResourceManager.GetString("infoTitle", resourceCulture);
            }
        }
        
        internal static string initialStartupMessage {
            get {
                return ResourceManager.GetString("initialStartupMessage", resourceCulture);
            }
        }
        
        internal static string installingLabel {
            get {
                return ResourceManager.GetString("installingLabel", resourceCulture);
            }
        }
        
        internal static string installLabel {
            get {
                return ResourceManager.GetString("installLabel", resourceCulture);
            }
        }
        
        internal static string languageString {
            get {
                return ResourceManager.GetString("languageString", resourceCulture);
            }
        }
        
        internal static string launchFailMessage {
            get {
                return ResourceManager.GetString("launchFailMessage", resourceCulture);
            }
        }
        
        internal static string launchFailTitle {
            get {
                return ResourceManager.GetString("launchFailTitle", resourceCulture);
            }
        }
        
        internal static string launchingLabel {
            get {
                return ResourceManager.GetString("launchingLabel", resourceCulture);
            }
        }
        
        internal static string launchLabel {
            get {
                return ResourceManager.GetString("launchLabel", resourceCulture);
            }
        }
        
        internal static string linuxTarget {
            get {
                return ResourceManager.GetString("linuxTarget", resourceCulture);
            }
        }
        
        internal static string localSettingsTitle {
            get {
                return ResourceManager.GetString("localSettingsTitle", resourceCulture);
            }
        }
        
        internal static string macTarget {
            get {
                return ResourceManager.GetString("macTarget", resourceCulture);
            }
        }
        
        internal static string malformedFTPURLMessage {
            get {
                return ResourceManager.GetString("malformedFTPURLMessage", resourceCulture);
            }
        }
        
        internal static string noPlatformMessage {
            get {
                return ResourceManager.GetString("noPlatformMessage", resourceCulture);
            }
        }
        
        internal static string noPlatformTitle {
            get {
                return ResourceManager.GetString("noPlatformTitle", resourceCulture);
            }
        }
        
        internal static string okString {
            get {
                return ResourceManager.GetString("okString", resourceCulture);
            }
        }
        
        internal static string optionsString {
            get {
                return ResourceManager.GetString("optionsString", resourceCulture);
            }
        }
        
        internal static string remoteSettingsTitle {
            get {
                return ResourceManager.GetString("remoteSettingsTitle", resourceCulture);
            }
        }
        
        internal static string repairFinishMessage {
            get {
                return ResourceManager.GetString("repairFinishMessage", resourceCulture);
            }
        }
        
        internal static string repairFinishTitle {
            get {
                return ResourceManager.GetString("repairFinishTitle", resourceCulture);
            }
        }
        
        internal static string repairingLabel {
            get {
                return ResourceManager.GetString("repairingLabel", resourceCulture);
            }
        }
        
        internal static string repairLabel {
            get {
                return ResourceManager.GetString("repairLabel", resourceCulture);
            }
        }
        
        internal static string settingsString {
            get {
                return ResourceManager.GetString("settingsString", resourceCulture);
            }
        }
        
        internal static string systemTargetString {
            get {
                return ResourceManager.GetString("systemTargetString", resourceCulture);
            }
        }
        
        internal static string updateLabel {
            get {
                return ResourceManager.GetString("updateLabel", resourceCulture);
            }
        }
        
        internal static string updatingLabel {
            get {
                return ResourceManager.GetString("updatingLabel", resourceCulture);
            }
        }
        
        internal static string usageTitle {
            get {
                return ResourceManager.GetString("usageTitle", resourceCulture);
            }
        }
        
        internal static string verifyingMessage {
            get {
                return ResourceManager.GetString("verifyingMessage", resourceCulture);
            }
        }
        
        internal static string warningTitle {
            get {
                return ResourceManager.GetString("warningTitle", resourceCulture);
            }
        }
        
        internal static string win32Target {
            get {
                return ResourceManager.GetString("win32Target", resourceCulture);
            }
        }
        
        internal static string win64Target {
            get {
                return ResourceManager.GetString("win64Target", resourceCulture);
            }
        }
        
        internal static string windowTitle {
            get {
                return ResourceManager.GetString("windowTitle", resourceCulture);
            }
        }
        
        internal static string inactiveLabel {
            get {
                return ResourceManager.GetString("inactiveLabel", resourceCulture);
            }
        }
    }
}
